version: '3.4'
services:
  apirest:
    restart: on-failure
    image: apirest
    build: 
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: 5000
    ports:
      - 5000:5000
    command: npm start
    volumes:
      - .:/app/
      - /app/node_modules
  
  postgres:
    image: postgres:11
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tyba_database_development